## 신경망 복습
### 1.1 수학과 파이썬 복습
#### 1.1.3 브로드 캐스트

In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
print(A * 10)

[[10 20]
 [30 40]]


In [3]:
b = np.array([10, 20])
print(A * b)

[[10 40]
 [30 80]]


#### 1.1.4 벡터의 내적과 행렬의 곱

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b) # 내적

32

In [5]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.matmul(A, B) # 행렬의 곱

array([[19, 22],
       [43, 50]])

#### 1.1.5 행렬 형상 확인
행렬의 곱에서는 대응하는 차원의 원소 수를 일치시켜야 한다.

 A    B  =  C
3x2  2x4   3x4